// src/vue/components/Footer.vue
<script>
    export default {
        data() {
            return { year: new Date().getFullYear() }
        }
    }
</script>

<template>
    <div class="medium-8 medium-offset-2 columns text-center">
        <small>©{{year}} <a href="//d3vl.com" class="d3vl-link">D3VL LTD</a></small><br>
        <small>BUILD: {{$build}}</small>
    </div>
</template>

// src/react/components/Footer.jsx
export default function Footer() {
    return (
        <div class="footer text-center p-3">
            <small>©{new Date().getFullYear()} <a href="https://d3vl.com" className="d3vl-link">D3VL LTD</a></small>
            <br />
            <small className="text-muted">Ver: 1.0.3</small>
        </div>
    );
}
